### PR TITLE
Added PITInfo

### PR DESCRIPTION
**Pull request by hallard**
I've Added PITinfo but as I'm noob in python and class that's the best I can do

I'd like to add (a fix) for UTInfo2, you hard coded the path with serial number, as UTInfo2 board as unique serial number this will works only with your module, so I think the best is to set port as parameter so we can use `/dev/ttyUSB1` or whatever.

Also I would like to add another parameter to handle Linky Standard Mode (9600bps)

Do you think you can handle these parameters or help me do do that I'm lost with class and way to pass parameters ?

Thanks

### CODE REVIEW

**Comment by demikl** [comment]
Hello, thanks for contributing. I'm not sure I can give some time to this project for the suggestions you mentioned. I'll let you know later.

**Comment by hallard** [comment]
No problem, I can live like that.

BTW, any chance to merge this PR ?

Thanks.

**Review by demikl — CHANGES_REQUESTED** [review]
New version should be 1.2.0 instead of 1.1.2 : the 1.1.X bump should only be used for bugfixes, not for new features.

Please also add some info to the CHANGELOG. Then I'll approve this pull request.

Thanks.

**Comment by demikl** [comment]
About your request for change on UTInfo2 and upper baudrate, this is already configurable, maybe you're asking about changing the default values ? I had not noticed that the hardcoded TTY device for the UTInfo2 board has a specific ID in it when I accepted the pull request #1 that introduced it.

```python
from teleinfo import Parser
from teleinfo.hw_vendors import UTInfo2
ti = Parser(UTInfo2(port="/dev/ttyAMA0", baudrate=9600))
print ti.get_frame()
```

**Comment by hallard** [comment]
That's done

ahah, so simple to change speed and port, I'm a "grosse quiche" in python 

I added 2 examples on readme

thanks

**Pull request merged**
